# Generated by Django 3.1.5 on 2021-01-28 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0002_module_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='class_room',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='module',
            name='length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='relations.album'),
        ),
    ]
